print('Enter your first name:')
firstname = input()
print('Enter your Surname:')
surname = input()
print('Enter your mobile no.')
mobileNo = input() 
print('Enter your post code.')
postcode = input() 
